# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a00aa6826637ed7757f6ff51c5f2c1cf65c0239058823c1979ee4d6e648602d4e804c64561f1fa1ac12ea226465da4f9f4014cb0068d6fc6f9a3f93a9dc2bc7e

test:
  secret_key_base: b3d662000fc7d409df95f004cf75f69a6126f8a96d383f01eed70778606e7554c1f75e0380cf70d3fdd6fb054b74246e1b3b7f58039c9afcbc93d883c1464dbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
